services:
  - name: backend
    type: web
    runtime: node
    buildCommand: "cd backend && yarn"
    startCommand: "cd backend && yarn start"
    envVars:
      - key: NODE_ENV
        value: production

  - name: dummy_remover
    type: web
    runtime: python
    buildCommand: "cd dummy_remover && pip install -r requirements.txt"
    startCommand: "cd dummy_remover && python dummyRemovalApi.py"
    envVars:
      - key: FLASK_ENV
        value: production
